#! /usr/bin/env bash
if [ $# < 1 ]; then
	echo "Needs at least 1 argument representing the program name";
	exit 1;
fi

# Create the root directory for the project
mkdir -p $1;

#Enter the root directory for the project
pushd .;
cd $1;

# Create directory structure
mkdir -p bin/ obj/main/ src/main/ test/;

# Create .gitkeep files to keep obj & bin directories in git
touch ./bin/.gitkeep
touch ./obj/.gitkeep

# Copy necessary files from /usr/local/lib/
cp /usr/local/lib/program_setup/cpp/Makefile .;
cp /usr/local/lib/program_setup/cpp/.ycm_extra_conf.py .;
cp /usr/local/lib/program_setup/cpp/_tests.cpp "./test/${1}_tests.cpp";
cp /usr/local/lib/program_setup/cpp/main.cpp ./src/main/;
cp /usr/local/lib/program_setup/cpp/.gitignore .;

# Install Unit Test Library
CATCH_URL="https://raw.github.com/philsquared/Catch/master/single_include/catch.hpp";
wget $CATCH_URL -O "test/catch.hpp";

# Setup git repo
git init;
git add .;
git commit -m "Initial Commit"

popd;

echo "Your application is ready";
